# Generated by Django 5.0.6 on 2024-06-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summariser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
