# Generated by Django 5.0.6 on 2024-06-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
